Repository SOFTENG310-2023/TimeWeaver, pull requests merged in 2023-08, with the labels that each got.

#2 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#11 Set Up Project Structure
  .gitignore
  .husky/pre-commit
  CONTRIBUTING.MD
  README.md
  index.js
  package-lock.json
  package.json
  public/assets/css/main.css
  public/assets/js/main.js
  public/index.html
Labels: documentation, enhancement

#13 Create a Basic UI
  public/assets/css/main.css
  public/index.html
Labels: enhancement

#17 Update GitHub Actions Workflow
  .github/workflows/build.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/test.yml
  jest.config.js
  package-lock.json
  package.json
Labels: bug, enhancement

#25 Calendar Addition Frontend Logic
  package.json
  public/assets/css/main.css
  public/index.html
  src/main.js
  src/manageCalendars.js
Labels: enhancement

#24 Add combine timetable feature
  package-lock.json
  package.json
  src/combine.js
  src/tests/combine.test.js
Labels: enhancement

#15 parser
  .idea/.gitignore
  .idea/assignment-1.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  eventsOutput.json
  package-lock.json
  package.json
  public/assets/js/main.js
  src/icalToJSON.js
  src/tests/icalToJSON.test.js
Labels: enhancement

#23 Add custom event
  eventsOutput.json
  package-lock.json
  package.json
  src/addCellTimetable.js
  src/combine.js
  src/icalToJSON.js
  src/tests/addCellTimetable.test.js
  src/tests/combine.test.js
  src/tests/icalToJSON.test.js
Labels: enhancement
